// src/actions/LibraryActionTypes.js

// === UC2: Listar Bibliotecas ===
export const FETCH_LIBRARIES_START = 'FETCH_LIBRARIES_START';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_ERROR = 'FETCH_LIBRARIES_ERROR';

// === UC3: Criar Biblioteca ===
export const CREATE_LIBRARY_START = 'CREATE_LIBRARY_START';
export const CREATE_LIBRARY_SUCCESS = 'CREATE_LIBRARY_SUCCESS';
export const CREATE_LIBRARY_ERROR = 'CREATE_LIBRARY_ERROR';

// === UC4: Editar Biblioteca ===
export const UPDATE_LIBRARY_START = 'UPDATE_LIBRARY_START';
export const UPDATE_LIBRARY_SUCCESS = 'UPDATE_LIBRARY_SUCCESS';
export const UPDATE_LIBRARY_ERROR = 'UPDATE_LIBRARY_ERROR';

// === UC5: Apagar Biblioteca ===
export const DELETE_LIBRARY_START = 'DELETE_LIBRARY_START';
export const DELETE_LIBRARY_SUCCESS = 'DELETE_LIBRARY_SUCCESS';
export const DELETE_LIBRARY_ERROR = 'DELETE_LIBRARY_ERROR';

// === UC6: Ver Livros Requisitados ===
export const FETCH_CHECKOUTS_START = 'FETCH_CHECKOUTS_START';
export const FETCH_CHECKOUTS_SUCCESS = 'FETCH_CHECKOUTS_SUCCESS';
export const FETCH_CHECKOUTS_ERROR = 'FETCH_CHECKOUTS_ERROR';

// === UC7/UC8: Checkin/Extend ===
export const CHECKIN_BOOK_SUCCESS = 'CHECKIN_BOOK_SUCCESS';
export const EXTEND_CHECKOUT_SUCCESS = 'EXTEND_CHECKOUT_SUCCESS';

// === UC1: Pesquisar Livros ===
export const SEARCH_BOOKS_START = 'SEARCH_BOOKS_START';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_ERROR = 'SEARCH_BOOKS_ERROR';